### ISSUE TITLE
zip signature verification failed

### ISSUE THREAD

**Issue by benediktg** [nvllsvm/freecyngn#16]
As I tried to flash the freecyngn-flashable-cm12.zip on my Android device (Samsung Galaxy S5 with Cyanogenmod 12.1 nightlies and TWRP 2.8.7.0) the process aborted because of an error `E:Zip signature verification failed: 1`. Lastly I could apply freecyngn by disabling the zip signature verification – could the flashable zip be signed by the developer?

**Comment by mejo-** [comment]
I have exactly the same issue on a device running the latest CM12.1 snapshot (not nightly) and the new CM recovery. I'll see whether the CM recovery supports disabling signature verification at all.

**Comment by mejo-** [comment]
Seems like there's no option in the new CM recovery to disable signature verification. So I'm out of luck here.

I manually removed the packages running the shell script commands through adb shell later (after adb root && adb remount). Is this sufficient? I read in the comments of another issue that it's important to flash freecyngn _before_ the first reboot after CM got flashed. Why is that? Does the first boot process write non-free apps somewhere into the system where it's impossible to remove them from afterwards? I'm really curious about that.
