### ISSUE TITLE
Consider including F-Droid APK in release

### ISSUE THREAD

**Issue by LuccoJ** [nvllsvm/freecyngn#23]
Due to having to remove Browser in the CM13 version of this, people will now potentially be unable to bootstrap the capacity to browse the web and install further apps.

Including a specific web browser would be arbitrary, unless the AOSP browser could be included with no Google dependencies; however, F-Droid includes various browsers (Lightning, for instance) and of course the ability to instantly install hundreds of Google-free applications. It would be a matter of installing the APK from within this script.

**Comment by nvllsvm** [comment]
I don't feel it's appropriate for this script to extend it's functionality beyond the removal of proprietary bits. It should do one thing and one thing only.

However, I wouldn't mind having a warning about this added in the README.

**Comment by nvllsvm** [comment]
Closing. Will not add F-Droid.
