### ISSUE TITLE
IMPORTANT: Searching for a new maintainer

### ISSUE THREAD

**Issue by mar-v-in** [nvllsvm/freecyngn#25]
As I do not use CyanogenMod anymore and do not have the time to contribute to freecyngn, i'd like to hand over maintainership to someone else.

If you think you can manage maintainership of freecyngn, just write here or mail me. Or if you think someone should maintain freecyngn, @-mention him/her.

**Comment by nvllsvm** [comment]
I'd be interested in taking ownership.

**Comment by mar-v-in** [comment]
@nvllsvm i sent you a request to take over "ownership" on GitHub

**Comment by nvllsvm** [comment]
@mar-v-in Accepted. Thanks!
