### ISSUE TITLE
Device doesn't initiate after wipe data / factory reset

### ISSUE THREAD

**Issue by mimi89999** [nvllsvm/freecyngn#28]
Because setupWizard was removed, the device doesn't initiate after wipe data / factory reset. That means: No notifications, home button doesn't work, limited power menu, etc.

Is there any solution for that?

**Comment by mglinux** [comment]
You could delete the /system/addon.d/20-freecyngn.sh through recovery file manager. 

Copy it elsewhere on sdcard before and after wiping/flashing copy it again to addon.d

**Comment by mimi89999** [comment]
I wiped data for some other reason...
Anyway, your solution is to run that partially non-free app and the solution for that issue would be to check what that app does and share some adb commands in a FAQ; make a script, that will do that or free that app.

**Comment by nvllsvm** [comment]
This has been resolved by having freecyngn update the CMSettings database.

https://github.com/nvllsvm/freecyngn/blob/1db806bbbf08c86ef32ec53d60e459736ed5f320/20-freecyngn.sh#L29

The procedure for clean installs has changed. See the README.

Release v1.1 includes this fix.
