### ISSUE TITLE
Nexus 5X: Home Button and Quick Settings broken

### ISSUE THREAD

**Issue by ffflorian** [nvllsvm/freecyngn#29]
After installing the newest nightly ([cm-13.0-20160729-NIGHTLY-bullhead](https://download.cyanogenmod.org/?device=bullhead)) and applying freecyngn, the home button has no function anymore and the Quick Settings are broken (can't pull down). I already tried installing a different Launcher and rebooting the device.

Edit: Everything works fine after removing
```
CMAccount
CMS
CMSetupWizard
CyanogenSetupWizard
```

from the list before applying. But I didn't try removing only one of these yet.

**Comment by brortao** [comment]
I had the same issue with the latest CM13 snapshot (cm-13.0-20160820) on a OnePlus 3. I went through the 4 list items, and the culprit is CyanogenSetupWizard. If you delete that line from the script, everything works.

**Comment by ffflorian** [comment]
Thanks @brortao for testing it!

**Comment by mar-v-in** [comment]
Is Provision.apk present in CM? This replaces the Google SetupWizard in AOSP.

**Comment by tristan-k** [comment]
@mar-v-in It is located `/system/app/Provision/Provision.apk`. I ran into the same issue with a i9300.

```
$ adb shell "cat /system/build.prop  | grep ro.cm"
ro.cm.device=i9300
ro.cm.build.version.plat.sdk=6
ro.cm.build.version.plat.rev=0
ro.cm.version=13.0-20160821-NIGHTLY-i9300
ro.cm.releasetype=NIGHTLY
ro.cmlegal.url=https://cyngn.com/legal/privacy-policy
ro.cm.display.version=13.0-20160821-NIGHTLY-i9300
```

**Comment by nvllsvm** [comment]
This has been resolved by manually updating the CMSettings database.

https://github.com/nvllsvm/freecyngn/blob/1db806bbbf08c86ef32ec53d60e459736ed5f320/20-freecyngn.sh#L29

The procedure for clean installs has changed. See the README.
